apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: web
      port: 3000 # Load Balancer Port
      targetPort: 80 # Target Port to the deployment
